"attribute" = "pink"
"type" = "yellow"
"type.enum.variant" = "teal"

"constructor" = "sapphire"

"constant" = "peach"
"constant.character" = "teal"
"constant.character.escape" = "pink"

"string" = "pink"
"string.regexp" = "pink"
"string.special" = "blue"
"string.special.symbol" = "red"

"comment" = { fg = "overlay2", modifiers = ["italic"] }

"variable" = "text"
"variable.parameter" = { fg = "pink", modifiers = ["italic"] }
"variable.builtin" = "red"
"variable.other.member" = "teal"

"label" = "sapphire"

"punctuation" = "overlay2"
"punctuation.special" = "sky"

"keyword" = "mauve"
"keyword.control.conditional" = { fg = "mauve", modifiers = ["italic"] }

"operator" = "sky"

"function" = "blue"
"function.macro" = "pink"

"tag" = "blue"

"namespace" = { fg = "yellow", modifiers = ["italic"] }

"special" = "blue"

"markup.heading.1" = "red"
"markup.heading.2" = "peach"
"markup.heading.3" = "yellow"
"markup.heading.4" = "green"
"markup.heading.5" = "sapphire"
"markup.heading.6" = "lavender"
"markup.list" = "teal"
"markup.list.unchecked" = "overlay2"
"markup.list.checked" = "green"
"markup.bold" = { fg = "pink", modifiers = ["bold"] }
"markup.italic" = { fg = "pink", modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["italic", "underlined"] }
"markup.link.text" = "lavender"
"markup.link.label" = "sapphire"
"markup.raw" = "pink"
"markup.quote" = "pink"

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "blue"

"ui.background" = { fg = "text", bg = "base" }

"ui.linenr" = { fg = "surface1" }
"ui.linenr.selected" = { fg = "lavender" }

"ui.statusline" = { fg = "subtext1", bg = "mantle" }
"ui.statusline.inactive" = { fg = "surface2", bg = "mantle" }
"ui.statusline.normal" = { fg = "base", bg = "blue", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "base", bg = "green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "base", bg = "mauve", modifiers = ["bold"] }

"ui.popup" = { fg = "text", bg = "surface0" }
"ui.window" = { fg = "crust" }
"ui.help" = { fg = "overlay2", bg = "surface0" }

"ui.bufferline" = { fg = "subtext0", bg = "mantle" }
"ui.bufferline.active" = { fg = "pink", bg = "base", underline = { color = "pink", style = "line" } }
"ui.bufferline.background" = { bg = "crust" }

"ui.text" = "pink"
"ui.text.focus" = { fg = "pink", bg = "surface0", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "pink" }
"ui.text.directory" = { fg = "sapphire" }

"ui.virtual" = "overlay0"
"ui.virtual.ruler" = { bg = "surface0" }
"ui.virtual.indent-guide" = "surface0"
"ui.virtual.inlay-hint" = { fg = "surface1", bg = "mantle" }
"ui.virtual.jump-label" = { fg = "rosewater", modifiers = ["bold"] }

"ui.selection" = { bg = "surface1" }

"ui.cursor" = { fg = "base", bg = "secondary_cursor" }
"ui.cursor.primary" = { fg = "base", bg = "pink" }
"ui.cursor.match" = { fg = "peach", modifiers = ["bold"] }

"ui.cursor.primary.normal" = { fg = "base", bg = "blue" }
"ui.cursor.primary.insert" = { fg = "base", bg = "green" }
"ui.cursor.primary.select" = { fg = "base", bg = "mauve" }

"ui.cursor.normal" = { fg = "base", bg = "overlay1" }
"ui.cursor.insert" = { fg = "base", bg = "teal" }
"ui.cursor.select" = { fg = "base", bg = "lavender" }

"ui.cursorline.primary" = { bg = "cursorline" }

"ui.highlight" = { bg = "surface1", modifiers = ["bold"] }

"ui.menu" = { fg = "overlay2", bg = "surface0" }
"ui.menu.selected" = { fg = "text", bg = "surface1", modifiers = ["bold"] }

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "sky", style = "curl" } }
"diagnostic.hint" = { underline = { color = "teal", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }

error = "red"
warning = "yellow"
info = "sky"
hint = "teal"

rainbow = ["red", "peach", "yellow", "green", "sapphire", "lavender"]

[palette]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#f4b8e4"
subtext1 = "#f4b8e4"
subtext0 = "#f4b8e4"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

cursorline = "#3a3f52"
secondary_cursor = "#f4b8e4"
secondary_cursor_select = "#ca9ee6"
secondary_cursor_normal = "#8caaee"
secondary_cursor_insert = "#81c8be"
