theme = "cat-frappe-pink"

[editor]
bufferline = "multiple"
color-modes = true
completion-trigger-len = 1
cursorline = true
default-yank-register = "+"
idle-timeout = 0
line-number = "relative"
scrolloff = 8

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
left = ["mode", "separator", "file-name", "file-modification-indicator"]
center = ["spinner"]
right = ["diagnostics", "selections", "position", "file-encoding"]
separator = ""

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.normal]
space.g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
space.e = [
  ":sh rm -f /tmp/unique-file-u41ae14",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-u41ae14",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-u41ae14}",
  ":redraw",
]
